// <auto-generated />
namespace CatchApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CatchApp_Added_Images : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CatchApp_Added_Images));
        
        string IMigrationMetadata.Id
        {
            get { return "201606081802365_CatchApp_Added_Images"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
